CCannedObject
{
	Object=CEntityAnimated
	{
		Dynamic Properties=1
		{
			Comment=Spirit Mana
		}
		Name=
		Child List=
		Visible=1
		Collideable=0
		Half Height=0
		Full Height=1
		Tries To Collide=0
		Has Hit Points=0
		Stationary=1
		Active=1
		Is Temporarily Excluded=0
		Is Marked For Deletion=0
		Activity=Array
		{
			Item Count=1
			Activity=CTouchingOvalTriggerAI
			{
				Marked For Deletion=0
				Publisher=
				Trigger Only Once=1
				Was Triggered=0
				Auto-Flip Switch=1
				Trigge Must Have HP=0
				Triggered By Anything=0
				Triggered By Players=1
				Triggered By Player Friends=0
				Triggered By Enemies=0
				Triggered By Projectiles=0
				Triggered By Name=
				Enter Action=CMultipleActionsAction
				{
					Action=Array
					{
						Item Count=3
						Action=CSpawnEffectAction
						{
							Explosion Model=Spell Effects/Shots/Spike Hit
							Location Entity=$Instigator
							Make effect a child of the location entity=1
							X Offset=0
							Y Offset=0
							Height Offset=0
							Play Default Sound=1
							Action to execute After Effect=
						}
						Action=CConditionalAction
						{
							Try Action=CExpressionAction
							{
								Expression=CIsGreaterThanOrEqual
								{
									Operand1=CVariableDerivedCharacterAttribute
									{
										Character Attribute=Derived Character Attributes/Mojo
									}
									Operator=
									Operand2=CConstant
									{
										Constant Value=16
									}
								}
								Character to get attributes from=$Instigator
							}
							Succeed Action=CActionDoDamage
							{
								Character Doing Damage=$trigger
								Character To Damage=$instigator
								Defend Against=1
								No Friendly Fire Check=0
								Damages=Array
								{
									Item Count=1
									Damage=CXRPGDamage
									{
										Damage Type=Damage Types/Piercing
										Damage Amount=CRandom
										{
											Operator=
											Minimum=CConstant
											{
												Constant Value=12
											}
											Maximum=CConstant
											{
												Constant Value=18
											}
										}
									}
								}
							}
							Fail Action=CConditionalAction
							{
								Try Action=CExpressionAction
								{
									Expression=CIsGreaterThanOrEqual
									{
										Operand1=CVariableDerivedCharacterAttribute
										{
											Character Attribute=Derived Character Attributes/Mojo
										}
										Operator=
										Operand2=CConstant
										{
											Constant Value=10
										}
									}
									Character to get attributes from=$Instigator
								}
								Succeed Action=CActionDoDamage
								{
									Character Doing Damage=$trigger
									Character To Damage=$instigator
									Defend Against=1
									No Friendly Fire Check=0
									Damages=Array
									{
										Item Count=1
										Damage=CXRPGDamage
										{
											Damage Type=Damage Types/Piercing
											Damage Amount=CRandom
											{
												Operator=
												Minimum=CConstant
												{
													Constant Value=8
												}
												Maximum=CConstant
												{
													Constant Value=12
												}
											}
										}
									}
								}
								Fail Action=CActionDoDamage
								{
									Character Doing Damage=$trigger
									Character To Damage=$instigator
									Defend Against=1
									No Friendly Fire Check=0
									Damages=Array
									{
										Item Count=1
										Damage=CXRPGDamage
										{
											Damage Type=Damage Types/Piercing
											Damage Amount=CRandom
											{
												Operator=
												Minimum=CConstant
												{
													Constant Value=5
												}
												Maximum=CConstant
												{
													Constant Value=9
												}
											}
										}
									}
								}
								Return failure if the TryAction failes=0
							}
							Return failure if the TryAction failes=0
						}
						Action=CDeleteAction
						{
							Target Name=$Trigger
						}
					}
				}
				Exit Action=
				Repeat Action=
				Repeat Every=0
				Touching LayerPart=
				Next Repeat Time=0
				X Radius=55
				YX Ratio=0.712766
			}
		}
		Category=
		Team Number=Nutral
		Used In=QuestMode
		Current Target=
		Publisher=
		Model=Spell Effects/Ground lights/Smoke
		Position X=0
		Position Y=0
		Rendering Height=0
		Rendering Height Float=0
		Cur Sequence=Idle
		Cur Damage=0
		Destroyed Script Action=
		Destroyed Effect Action=
		Damaged Script Action=
		Damaged Effect Action=
		Hit Action=
		Default Death Type=!None
		Has Done Death Processing=0
		Play Ratio=0
		Aiming Angle=0
		Movement Angle=0
		Start FacingAngle=0
		Current Frame=0
		Created By=
		BehaviorStack=CEntityBehaviorStack
		{
			InProcess=0
			Blocking Priority=Idle
			BehaviorList=Array
			{
				Item Count=0
			}
		}
		Facing Backwards=0
		Last Facing Backwards=0
		Upper Body Present=0
		Synch Aiming And Moving=1
		Frame Index Locked=0
		Waiting For Discharge=0
		Still Shooting=0
		Trying To Move=0
		Tracking Updates Since Relocate=0
	}
	Use=Shared Global Instance
}
