CCannedObject
{
	Object=CInventoryItemGeneratorMojoList
	{
		Mojo Expression=CAverageMojo
		{
		}
		Items=Array
		{
			Array Count=3
			Array Item=CInventoryItemGeneratorMojoListItem
			{
				Max Mojo=7
				Item=CInventoryItemGeneratorCannedList
				{
					Canned Item List=Inventory/Creating Random Magic Items/Implementation Folder DO NOT PICK FROM/Magic Equipment LOW Mojo
				}
			}
			Array Item=CInventoryItemGeneratorMojoListItem
			{
				Max Mojo=16
				Item=CInventoryItemGeneratorCannedList
				{
					Canned Item List=Inventory/Creating Random Magic Items/Implementation Folder DO NOT PICK FROM/Magic Equipment MEDIUM Mojo
				}
			}
			Array Item=CInventoryItemGeneratorMojoListItem
			{
				Max Mojo=999
				Item=CInventoryItemGeneratorCannedList
				{
					Canned Item List=Inventory/Creating Random Magic Items/Implementation Folder DO NOT PICK FROM/Magic Equipment HIGH Mojo
				}
			}
		}
	}
	Use=Shared Global Instance
}
