CCannedObject
{
	Object=CInventoryItemGeneratorMixedList
	{
		Items=Array
		{
			Array Count=6
			Array Item=CInventoryItemGeneratorMixedListItem
			{
				Weighting=10
				Item=CInventoryItemGeneratorCannedList
				{
					Canned Item List=Inventory/Generator Combinations/Misc Items/Amulet selection MAGIC MEDIUM Mojo
				}
			}
			Array Item=CInventoryItemGeneratorMixedListItem
			{
				Weighting=10
				Item=CInventoryItemGeneratorCannedList
				{
					Canned Item List=Inventory/Generator Combinations/Misc Items/Belt selection MAGIC MEDIUM Mojo
				}
			}
			Array Item=CInventoryItemGeneratorMixedListItem
			{
				Weighting=10
				Item=CInventoryItemGeneratorCannedList
				{
					Canned Item List=Inventory/Generator Combinations/Misc Items/Bracer selection MAGIC MEDIUM Mojo
				}
			}
			Array Item=CInventoryItemGeneratorMixedListItem
			{
				Weighting=10
				Item=CInventoryItemGeneratorCannedList
				{
					Canned Item List=Inventory/Generator Combinations/Misc Items/Cloak selection MAGIC MEDIUM Mojo
				}
			}
			Array Item=CInventoryItemGeneratorMixedListItem
			{
				Weighting=10
				Item=CInventoryItemGeneratorCannedList
				{
					Canned Item List=Inventory/Generator Combinations/Misc Items/Helmet selection MAGIC MEDIUM Mojo
				}
			}
			Array Item=CInventoryItemGeneratorMixedListItem
			{
				Weighting=10
				Item=CInventoryItemGeneratorCannedList
				{
					Canned Item List=Inventory/Generator Combinations/Misc Items/Ring selection MAGIC MEDIUM Mojo
				}
			}
		}
	}
	Use=Shared Global Instance
}
