CCannedObject
{
	Object=CIfAction
	{
		If=CExpressionAction
		{
			Expression=CIsGreaterThan
			{
				Operand1=CVariableDerivedCharacterAttribute
				{
					Character Attribute=Derived Character Attributes/Uber Perks/Goblin Rank
				}
				Operator=
				Operand2=CConstant
				{
					Constant Value=2
				}
			}
			Character to get attributes from=$Instigator
		}
		Then=CMultipleActionsAction
		{
			Action=Array
			{
				Item Count=2
				Action=CAssignFactionToCharacterAction
				{
					Faction To Assign=Factions/Goblin Traitor - Fallen Champion
					Character To assign=$Instigator
				}
				Action=CGiveCharacterPerkAction
				{
					Character to give perk to=$Instigator
					Perk to give=Perks/!Event Title Perks/Goblin Traitor
				}
			}
		}
		Else=CIfAction
		{
			If=CExpressionAction
			{
				Expression=CIsGreaterThan
				{
					Operand1=CVariableDerivedCharacterAttribute
					{
						Character Attribute=Derived Character Attributes/Uber Perks/Goblin Rank
					}
					Operator=
					Operand2=CConstant
					{
						Constant Value=0
					}
				}
				Character to get attributes from=$Instigator
			}
			Then=CMultipleActionsAction
			{
				Action=Array
				{
					Item Count=2
					Action=CAssignFactionToCharacterAction
					{
						Faction To Assign=Factions/Goblin Traitor - Bad Blood
						Character To assign=$Instigator
					}
					Action=CGiveCharacterPerkAction
					{
						Character to give perk to=$Instigator
						Perk to give=Perks/!Event Title Perks/Goblin Traitor
					}
				}
			}
			Else=CMultipleActionsAction
			{
				Action=Array
				{
					Item Count=2
					Action=CAssignFactionToCharacterAction
					{
						Faction To Assign=Factions/Goblin Traitor - Foe
						Character To assign=$Instigator
					}
					Action=CGiveCharacterPerkAction
					{
						Character to give perk to=$Instigator
						Perk to give=Perks/!Event Title Perks/Goblin Traitor
					}
				}
			}
			Return failure if the If failes=0
		}
		Return failure if the If failes=0
	}
	Use=Shared Global Instance
}
