CCannedObject
{
	Object=CAND
	{
		Operand1=CActionExpression
		{
			Action=CActionCheckForInventoryItem
			{
				Who to give check=$instigator
				Inventory Item To Check For=Inventory/Specific Item Cans/Quest Items/Hangover Cure Potion
			}
		}
		Operator=
		Operand2=CActionExpression
		{
			Action=CIsQuestStateTheCurrentStateAction
			{
				Quest=Levels/1 Barcelona/Quests/Gate District/Gather Nightshade Root for Quinn
				State=B6CRM8YF
			}
		}
	}
	Use=Shared Global Instance
}
